#!/bin/sh
STD_VERSION="c++17"
OPTIMIZATION_LEVEL="O2"

echo "Building $1 and running..."

# Compiling executable
g++ "$1" \
benchmark/timer.hpp \
benchmark/timer.cpp \
-std=$STD_VERSION \
-Wall -Wpedantic -Werror \
-$OPTIMIZATION_LEVEL \

# Running compiled output
./a.out

# Cleaning up
find . -name "*.out" -type f -delete
find . -name "*.hpp.gch" -type f -delete

