#!/bin/sh
STD_VERSION="c++20"
OPTIMIZATION_LEVEL="O2"

echo "Building $1 and running..."

g++ "$1" \
benchmark/timer.hpp \
benchmark/timer.cpp \
-std=$STD_VERSION \
-Wall -Wpedantic -Werror \
-$OPTIMIZATION_LEVEL \

./a.out

rm -f a.out
